In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [5]:
employees = pd.read_csv("../datasets/employees.csv")

insider = pd.read_csv("../datasets/insider_threat_clean_dataset.csv")

reimbursement = pd.read_excel("../datasets/reimbursement_fraud_dataset.xlsx")

procurement = pd.read_csv("../datasets/procurement.csv")

vendors = pd.read_csv("../datasets/vendors.csv")

payroll = pd.read_csv("../datasets/payroll.csv")

salary = pd.read_csv("../datasets/salary_grade.csv")

In [6]:
print("Employees:", employees.shape)
print("Insider:", insider.shape)
print("Reimbursement:", reimbursement.shape)
print("Procurement:", procurement.shape)
print("Vendors:", vendors.shape)
print("Payroll:", payroll.shape)
print("Salary:", salary.shape)

Employees: (196, 6)
Insider: (118614, 22)
Reimbursement: (5000, 7)
Procurement: (278, 9)
Vendors: (25, 4)
Payroll: (196, 8)
Salary: (5, 3)

In [7]:
employees.head()

  employee_id   employee_name  department    position grade  tenure_years
0     EMP1000    Raka Saputra  Operations     Manager    G1           4.7
1     EMP1001   Salsa Nugraha   Marketing      Senior    G1           2.8
2     EMP1002  Tegar Maharani          IT  Supervisor    G3           1.4
3     EMP1003     Ulfa Kusuma   Marketing     Manager    G3           2.2
4     EMP1004    Vina Permata   Marketing       Staff    G3           9.4

In [8]:
insider.head()

,employee_department,employee_campus,employee_position,employee_seniority_years,is_contractor,employee_classification,has_foreign_citizenship,has_criminal_record,has_medical_history,employee_origin_country,...,total_files_burned,burned_from_other,is_abroad,trip_day_number,hostility_country_level,num_entries,num_unique_campus,late_exit_flag,entry_during_weekend,is_malicious
0,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,4,0,0,0.0,0,1,1,0,1,0
1,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,1,1,0,0,0
2,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,2,0,0,0.0,0,1,1,0,0,0
3,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,1,1,0,0,0
4,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,0,0,0,0,0

In [9]:
reimbursement.head()

,Employee_ID,Department,Expense_Type,Claim_Amount,Claim_Date,Approval_Status,Fraud_Label
0,E621,HR,Fuel,10973.03,2024-06-20,Approved,0
1,E354,Operations,Hotel,2036.92,2024-07-23,Pending,0
2,E823,IT,Travel,3813.36,2025-01-21,Pending,0
3,E710,Sales,Training,14152.43,2024-12-20,Approved,0
4,E123,Finance,Hotel,1920.93,2025-08-12,Pending,0

In [10]:
print("Employees Columns:")
print(employees.columns)

print("\nInsider Columns:")
print(insider.columns)

print("\nReimbursement Columns:")
print(reimbursement.columns)

print("\nProcurement Columns:")
print(procurement.columns)

print("\nVendors Columns:")
print(vendors.columns)

print("\nPayroll Columns:")
print(payroll.columns)

print("\nSalary Columns:")
print(salary.columns)

Employees Columns:
Index(['employee_id', 'employee_name', 'department', 'position', 'grade',
       'tenure_years'],
      dtype='str')

Insider Columns:
Index(['employee_department', 'employee_campus', 'employee_position',
       'employee_seniority_years', 'is_contractor', 'employee_classification',
       'has_foreign_citizenship', 'has_criminal_record', 'has_medical_history',
       'employee_origin_country', 'total_printed_pages',
       'num_printed_pages_off_hours', 'total_files_burned',
       'burned_from_other', 'is_abroad', 'trip_day_number',
       'hostility_country_level', 'num_entries', 'num_unique_campus',
       'late_exit_flag', 'entry_during_weekend', 'is_malicious'],
      dtype='str')

Reimbursement Columns:
Index(['Employee_ID', 'Department', 'Expense_Type', 'Claim_Amount',
       'Claim_Date', 'Approval_Status', 'Fraud_Label'],
      dtype='str')

Procurement Columns:
Index(['procurement_id', 'employee_id', 'vendor_id', 'price_system',
       'price_actual', 'price_difference', 'account_mismatch_flag',
       'fraud_flag', 'fraud_probability'],
      dtype='str')

Vendors Columns:
Index(['vendor_id', 'vendor_name', 'bank_name', 'account_number'], dtype='str')

Payroll Columns:
Index(['employee_id', 'salary_system', 'salary_received', 'salary_difference',
       'checker_approved', 'signer_approved', 'fraud_flag',
       'fraud_probability'],
      dtype='str')

Salary Columns:
Index(['grade', 'base_salary', 'allowance'], dtype='str')

In [11]:
print("Employees Missing:")
print(employees.isnull().sum())

print("\nInsider Missing:")
print(insider.isnull().sum())

print("\nReimbursement Missing:")
print(reimbursement.isnull().sum())

print("\nProcurement Missing:")
print(procurement.isnull().sum())

print("\nPayroll Missing:")
print(payroll.isnull().sum())

Employees Missing:
employee_id      0
employee_name    0
department       0
position         0
grade            0
tenure_years     0
dtype: int64

Insider Missing:
employee_department            0
employee_campus                0
employee_position              0
employee_seniority_years       0
is_contractor                  0
employee_classification        0
has_foreign_citizenship        0
has_criminal_record            0
has_medical_history            0
employee_origin_country        0
total_printed_pages            0
num_printed_pages_off_hours    0
total_files_burned             0
burned_from_other              0
is_abroad                      0
trip_day_number                0
hostility_country_level        0
num_entries                    0
num_unique_campus              0
late_exit_flag                 0
entry_during_weekend           0
is_malicious                   0
dtype: int64

Reimbursement Missing:
Employee_ID        0
Department         0
Expense_Type       0
Claim_Amount       0
Claim_Date         0
Approval_Status    0
Fraud_Label        0
dtype: int64

Procurement Missing:
procurement_id             0
employee_id                0
vendor_id                  0
price_system               0
price_actual               0
price_difference           0
account_mismatch_flag      0
fraud_flag                 0
fraud_probability        275
dtype: int64

Payroll Missing:
employee_id            0
salary_system          0
salary_received        0
salary_difference      0
checker_approved       0
signer_approved        0
fraud_flag             0
fraud_probability    195
dtype: int64

In [12]:
print("Reimbursement Fraud:")
print(reimbursement['Fraud_Label'].value_counts())

print("\nProcurement Fraud:")
print(procurement['fraud_flag'].value_counts())

print("\nPayroll Fraud:")
print(payroll['fraud_flag'].value_counts())

Reimbursement Fraud:
Fraud_Label
0    4594
1     406
Name: count, dtype: int64

Procurement Fraud:
fraud_flag
0    191
1     87
Name: count, dtype: int64

Payroll Fraud:
fraud_flag
0    128
1     68
Name: count, dtype: int64

In [13]:
reimbursement = pd.read_excel("../datasets/reimbursement.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../datasets/reimbursement.xlsx'

In [14]:
reimbursement = pd.read_excel("../datasets/improved_reimbursement_fraud_dataset(1).xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../datasets/improved_reimbursement_fraud_dataset(1).xlsx'

In [15]:
reimbursement.shape

(5000, 7)

In [16]:
reimbursement = pd.read_excel("../datasets/improved_reimbursement_fraud_dataset.xlsx")

In [17]:
reimbursement.shape

(5000, 18)

In [18]:
reimbursement.columns

Index(['Employee_ID', 'Department', 'Expense_Type', 'Claim_Amount',
       'Claim_Date', 'Approval_Status', 'Fraud_Label', 'Designation',
       'Employee_Tenure_Months', 'Manager_ID', 'Receipt_Available',
       'Duplicate_Claim', 'Previous_Claims_Count', 'Approval_Time_Days',
       'Weekend_Claim', 'Policy_Violation_Count', 'Payment_Method',
       'Risk_Score'],
      dtype='str')